# Adapted from:
# https://bevy.org/learn/quick-start/getting-started/setup/
#

[target.x86_64-unknown-linux-gnu]
linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-Zshare-generics=y"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-Zshare-generics=y"]


[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
